from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
def build_pdf_report(applicant, probability, level, reasons, model_name):
    out=BytesIO(); doc=SimpleDocTemplate(out,pagesize=A4,rightMargin=42,leftMargin=42); styles=getSampleStyleSheet(); story=[Paragraph("LendSight — Credit Risk Assessment",styles["Title"]),Spacer(1,14),Paragraph(f"Risk classification: <b>{level}</b> &nbsp;&nbsp; | &nbsp;&nbsp; Default probability: <b>{probability:.1%}</b>",styles["Heading2"]),Spacer(1,12)]
    rows=[["Applicant field","Value"]]+[[k.replace("_"," "),str(v)] for k,v in applicant.items()]
    t=Table(rows,colWidths=[190,300]); t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#0f766e")),("TEXTCOLOR",(0,0),(-1,0),colors.white),("GRID",(0,0),(-1,-1),.25,colors.lightgrey),("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTSIZE",(0,0),(-1,-1),8),("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white,colors.HexColor("#f0fdfa")])]))
    story += [t,Spacer(1,15),Paragraph("Key risk signals",styles["Heading2"])] + [Paragraph("• "+r,styles["BodyText"]) for r in reasons] + [Spacer(1,12),Paragraph(f"Generated by {model_name}. This educational report supports human review and is not a lending decision.",styles["Italic"])]
    doc.build(story); return out.getvalue()
